on: [push]

name: build and test docker image

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pgge
      - name: Run a test on the DRB1-3123 dataset dbg
        run: docker run -v ${PWD}/data/:/data pgge "pgge -g '/data/HLA/DRB1-3123/*.consensus*.gfa' -f /data/HLA/DRB1-3123/DRB1-3123.fa -r /scripts/beehave.R -t 2 -o /data/HLA/DRB1-3123/pgge_docker -l 1000 -s 1000 -p 100"
      - name: Run a test on the DRB1-3123 dataset vg
        run: docker run -v ${PWD}/data/:/data pgge "pgge -g '/data/HLA/DRB1-3123/*.consensus*.gfa' -f /data/HLA/DRB1-3123/DRB1-3123.fa -r /scripts/beehave.R -t 2 -o /data/HLA/DRB1-3123/pgge_docker -l 1000 -s 2000 -p 10 --graphaligner-vg-mode"
